### ISSUE TITLE
Error running main on defaults

### ISSUE THREAD

**Issue by dawson-miller** [AlanDongMu/TimeGAN_PytorchRebuild#2]
When running main with the defaults, I receive this error regarding line 47 of run.py and line 89 in train_embedder():

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

I have tried setting retain_graph=True but the error does not go away.

**Comment by AlanDongMu** [comment]
I'm sorry that i can't reproduce the error you received, maybe you can provide more information about it.
By the way, line 47 of run.py does not related to line 89 in rain_embedder(), so maybe you should check the code you are running.

**Comment by dawson-miller** [comment]
I am using python 3.9.15, pytorch 1.13.1, with cuda 11.7.1. 

I just re-cloned the repo and still getting the error. I'm attaching the spec file to my conda environment. Would you be able to tell me the python, pytorch, and cuda versions you are using?

Here is a screenshot of the error: (python3 main.py --iterations=10)
![image](https://github.com/AlanDongMu/TimeGAN_PytorchRebuild/assets/82901642/bd3a6bfc-4a0a-4fb4-90d6-536d9353cd9f)


[timegan_torch_conda_env.txt](https://github.com/AlanDongMu/TimeGAN_PytorchRebuild/files/13930367/timegan_torch_conda_env.txt)

Thanks.

**Comment by AlanDongMu** [comment]
Thanks for your issue!
I can reproduce this error now. when “joint training”, retain_graph=True should be set to train_generator() https://github.com/AlanDongMu/TimeGAN_PytorchRebuild/blob/cad34e35ca53b3d80b408cec9f642a3615bc87a3/timegan.py#L120

However, there remains a bug caused by some in-place operations happened when “joint training”. It could work in some early version Pytorch, but no the requirement I provided. So I will fix this bug by modify the code as soon as possible.

Sorry that i have made a mistake. I recently change the code in  “joint training” part  for last issue(closed already) without careful check, which may causes the error you get.

Your issue is very helpful, thanks a lot. I will remind you when i have fixed these buges.

**Comment by AlanDongMu** [comment]
The error has been resolved. 
You can check the latest code.

**Comment by dawson-miller** [comment]
Thanks! Can confirm it runs to completion.
